name: stack_overflow
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.2+1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  intl: ^0.18.0
  date_field: ^5.0.1
  dartz: ^0.10.1
  retry: ^3.1.2
  connectivity_plus: ^6.0.2
  better_player: ^0.0.83
  just_audio: ^0.9.37
  audio_session: ^0.1.19
  scrollable_list_tab_scroller: ^0.2.0
  azlistview: 
    git: 
      url: https://github.com/ramkshukla/azlistview.git
      ref: master
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
