name: junior_journey
description: "kids learning app"
publish_to: 'none' 
version: 1.0.0+7
environment:
    sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.2
  flutter_tts: ^3.8.5
  audioplayers: ^5.2.1
  cached_network_image: ^3.3.1
  fluttertoast: ^8.2.4
 

 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/images/   
    - assets/images1/  
    - assets/images2/  
    - assets/audio/ 
 
